export const tacSection = [
	{
		title: '1. Use of the Services',
		content: `This Terms of Service Agreement (the “Agreement”) explains the terms and conditions by which you may access and use the Open Protocol. It is important that you must read this Agreement carefully. By accessing or using the Protocol, you signify that you have read, understand, and agree to be bound by this Agreement in its entirety. If you do not agree, you are not authorized to access or use the Protocol. To use the Protocol and all features in its entirety (the “Services”), you must legally be able to enter into the Agreement. By using the Services, you represent and warrant that you meet the eligibility requirement. If you do not meet the requirement, you must not access or use the Protocol or the Services.
For the avoidance of doubt, wallets connecting to Hashstack are provided by external providers and by selecting you agree to Terms of those providers (please refer to Argent & Braavos). Your access to the wallet might be reliant on the external providers being operational. Open Protocol makes no representations or warranties on behalf of these external providers, and the Protocol owes no obligation and liabilities in relation to the operations and safety of these providers.`,
	},
	{
		title: '2. Eligibility',
		content: `To access or use the Protocol, you must be able to form a legally binding contract with us. Accordingly, you represent that you are at least eighteen years old and have the full right, power, and authority to enter into and comply with the terms and conditions of this Agreement on behalf of yourself and any company or legal entity for which you may access or use the Protocol. You further represent that you are not a citizen, resident, or member of any jurisdiction or group that is subject to economic sanctions by the United States, or where your use of the Protocol would be illegal or otherwise violate any applicable law. You further represent that your access and use of the Protocol will fully comply with all applicable laws and regulations, and that you will not access or use the Protocol to conduct, promote, or otherwise facilitate any illegal activity.`,
	},
	{
		title: '3. Prohibited Content and Activity',
		content: `You agree to only use the Services in compliance with this Agreement (including, without limitation, these Terms), applicable third-party policies, and all applicable laws, rules, regulations and related guidance. The following conduct and activities are prohibited:

    - Financial Crimes. Activity to promote or facilitate illegal activity (including, without limitation, money laundering, financing terrorism, tax evasion, buying or selling illegal drugs, contraband, counterfeit goods, or illegal weapons, as well as engage in anticompetitive behavior or other unlawful misconduct);
    - Intellectual Property Infringement. Activity that infringes on or violates any copyright, trademark, service mark, patent, right of publicity, right of privacy, or other proprietary or intellectual property rights under the law;
    - Cyberattack. Activity that seeks to interfere with or compromise the integrity, security, or proper functioning of any computer, server, network, personal device, or other information technology system, including (but not limited to) the deployment of viruses, denial-of-service attacks, uploading or transmitting viruses, worms, Trojan horses, time bombs, cancel bots, spiders, malware or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Services;
    - Fraud and Misrepresentation. Activity that seeks to defraud us or any other person or entity, including (but not limited to) providing any false, inaccurate, or misleading information in order to unlawfully obtain the property of another;
    - Market Manipulation. Activity that violates any applicable law, rule, or regulation concerning the integrity of trading markets, including (but not limited to) the manipulative tactics commonly known as spoofing and wash trading;
    - Unauthorized Uses of the Software. Activity that seeks to exploit the Services for any unauthorized commercial purpose; copy or make unauthorized use of all or any portion of the Services, including by attempting to reverse compile, reformatting or framing, disassemble, reverse engineer any part of the Services; harvest or otherwise collect information from the Services for any unauthorized purpose; use the Services under false or fraudulent pretenses or otherwise being deceitful; and interferes with other users’ access to or use of the Services;`,
	},
	{
		title: '4. Proprietary Rights',
		content: `We own all intellectual property and other rights in the Protocol and its contents, including (but not limited to) software, interface, text, images, trademarks, service marks, copyrights, patents, and designs. Unless expressly authorized by us, you may not copy, modify, adapt, rent, license, sell, publish, distribute, or otherwise permit any third party to access or use the Protocol or any of its contents. Provided that you are eligible, you are hereby granted a single, personal, limited license to access and use the Protocol. This license is non-exclusive, non-transferable, and freely revocable by us at any time without notice or cause. Use of the Protocol or its contents for any purpose not expressly permitted by this Agreement is strictly prohibited. The Protocol comprises open-source software and smart contracts running on the public Ethereum blockchain, which shall not be deemed our proprietary property.`,
	},
	{
		title: '5. Privacy',
		content: `We value your privacy, and we will work to provide reasonable diligence in handling and to safeguard in preserving its integrity and security. We use commercially reasonable safeguards to preserve the integrity and security of your personally identifiable information (“PII”) and aggregate data. However, we cannot guarantee that unauthorized third parties will never be able to obtain or use your PII or aggregate data for improper purposes. You acknowledge that you provide your PII and aggregate data at your own risk. By accessing and using the Protocol, you understand and consent to our collection, use, and disclosure of your PII and aggregate data. We are also abided by and will comply with valid regulatory requests, subpoena requests and/or any other form of such requests required by law, and we will carefully consider each request to ensure that it comports with the spirit and letter of the law, and we will not hesitate to challenge invalid, overbroad, or unconstitutional requests as appropriate.`,
	},
	{
		title: '6. No Representations and Warranties',
		content: `The Protocol is provided on an “AS IS” and “AS AVAILABLE” basis. To the fullest extent permitted by law, we disclaim any representations and warranties of any kind, whether express, implied, or statutory, including (but not limited to) the warranties of merchantability and fitness for a particular purpose. You acknowledge and agree that your use of the Protocol is at your own risk. We do not represent or warrant that access to the Protocol will be continuous, uninterrupted, timely, or secure; that the information contained in the Protocol will be accurate, reliable, complete, or current; or that the Protocol will be free from errors, defects, viruses, or other harmful elements. No advice, information, or statement that we make should be treated as creating any warranty concerning the Protocol. We do not endorse, guarantee, or assume responsibility for any advertisements, offers, or statements made by third parties concerning the Protocol. Before you make any financial, legal, or other decisions involving the Protocol, you should seek independent professional advice from an individual who is licensed and qualified in the area for which such advice would be appropriate.`,
	},
	{
		title: '7. No Fiduciary Duties',
		content: `This Agreement is not intended to, and does not, create or impose any fiduciary duties on us. To the fullest extent permitted by law, you acknowledge and agree that we owe no fiduciary duties or liabilities to you or any other party, and that to the extent any such duties or liabilities may exist at law or in equity, those duties and liabilities are hereby irrevocably disclaimed, waived, and eliminated. You further agree that the only duties and obligations that we owe you are those set out expressly in this Agreement.`,
	},
	{
		title: '8. Compliance Obligations',
		content: `The Protocol may not be available or appropriate for use in your jurisdictions. While we take appropriate measures to prevent access from unauthorized jurisdictions, you agree that you are solely and entirely responsible for compliance with all laws and regulations that may apply to you by accessing or using the Protocol. You may not use the Protocol if you are a citizen, resident, or member of any jurisdiction or group that is subject to sanctions by the Office of Foreign Assets Control (OFAC) by the United States, or if your use of the Protocol would be illegal or otherwise violate any applicable law.`,
	},
	{
		title: '9. Assumption of Risk',
		content: `By accessing and using the Protocol, you represent that you understand the inherent risks associated with using cryptographic and blockchain-based systems, and that you have a working knowledge of the usage and intricacies of digital assets such as bitcoin (BTC), ether (ETH), and other digital tokens such as those following the Ethereum Token Standard (ERC-20). You further understand that the markets for these digital assets are highly volatile due to factors including (but not limited to) adoption, speculation, technology, security, and regulation. You acknowledge that the cost and speed of transacting with cryptographic and blockchain-based systems such as Ethereum are variable and may increase dramatically at any time. You further acknowledge the risk that your digital assets may lose some or all of their value while they are supplied to the Protocol. If you borrow digital assets from the Protocol, you will have to supply digital assets of your own as collateral. If your collateral declines in value such that it is no longer sufficient to secure the amount that you borrowed, others may interact with the Protocol to seize your collateral in a liquidation event. You further acknowledge that we are not responsible for any of these variables or risks, do not own or control the Protocol, and cannot be held liable for any resulting losses that you experience while accessing or using the Protocol. Accordingly, you understand and agree to assume full responsibility for all of the risks of accessing and using the Protocol and interacting with the Protocol.`,
	},
	{
		title: '10. Limitation of Liability',
		content: `Under no circumstances shall we or any of our officers, directors, employees, contractors, agents, affiliates, or subsidiaries (collectively the “Indemnified Parties”) be liable to you for any indirect, punitive, incidental, special, consequential, or exemplary damages, including (but not limited to) damages for loss of profits, goodwill, use, data, or other intangible property, arising out of or relating to any access or use of the Protocol, nor will we be responsible for any damage, loss, or injury resulting from hacking, tampering, or other unauthorized access or use of the Protocol or the information contained within it. We assume no liability or responsibility for any: (a) errors, mistakes, or inaccuracies of content; (b) personal injury or property damage, of any nature whatsoever, resulting from any access or use of the Protocol; (c) unauthorized access or use of any secure server or database in our control, or the use of any information or data stored therein; (d) interruption or cessation of function related to the Protocol; (e) bugs, viruses, trojan horses, or the like that may be transmitted to or through the Protocol; (f) the malfunction, unexpected function or unintended function of the blockchain, any computer or cryptoasset network (including any wallet provider), including without limitation losses associated with network forks, replay attacks, double-spend attacks, sybil attacks, 51% attacks, governance disputes, mining difficulty, changes in cryptography or consensus rules, hacking, or cybersecurity breaches, (g) errors or omissions in, or loss or damage incurred as a result of the use of, any content made available through the Protocol; and (h) the defamatory, offensive, or illegal conduct of any third party. Under no circumstances shall we or any of our officers, directors, employees, contractors, agents, affiliates, or subsidiaries be liable to you for any claims, proceedings, liabilities, obligations, damages, losses, or costs in an amount exceeding the amount you paid to us in exchange for access to and use of the Protocol, or US$100.00, whichever is greater. This limitation of liability applies regardless of whether the alleged liability is based on contract, tort, negligence, strict liability, or any other basis, and even if we have been advised of the possibility of such liability. Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of certain liabilities and damages. Accordingly, some of the disclaimers and limitations set forth in this Agreement may not apply to you. This limitation of liability shall apply to the fullest extent permitted by law.
This limitation of liability is intended to apply without regard to whether other provisions of these terms have been breached or have proven ineffective. The limitations set forth in this section shall apply regardless of the form of action, whether the asserted liability or damages are based on contract, indemnification, tort, strict liability, statute, or any other legal or equitable theory, and whether or not the Indemnified Parties have been informed of the possibility of any such damage.
Some jurisdictions do not allow the exclusion or limitation of certain warranties and liabilities provided in this Section; accordingly, some of the above limitations and disclaimers may not apply to you. To the extent applicable law does not permit the Indemnified Parties to disclaim certain warranties or limit certain liabilities, the extent of the Indemnified Parties’ liability and the scope of any such warranties will be as permitted under applicable law.`,
	},
	{
		title: '11. Indemnification',
		content: `You agree to indemnify, defend, and hold harmless the Indemnified Parties from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of: (a) your breach or alleged breach of the Agreement (including, without limitation, these Terms); (b) anything you contribute to the Services; (c) your misuse of the Services, or any smart contract and/or script related thereto; (d) your violation of any laws, rules, regulations, codes, statutes, ordinances, or orders of any governmental or quasi-governmental authorities; (e) your violation of the rights of any third party, including any intellectual property right, publicity, confidentiality, property, or privacy right; (f) your use of a third-party product, service, and/or website; or (g) any misrepresentation made by you. We reserve the right to assume, at your expense, the exclusive defense and control of any matter subject to indemnification by you. You agree to cooperate with our defense of any claim. You will not in any event settle any claim without our prior written consent.`,
	},
	{
		title: '12. Waiver of Injunctive or Other Equitable Relief',
		content: `To the maximum extent permitted by law, you agree that you will not be permitted to obtain an injunction or other equitable relief of any kind, such as any court or other action that may interfere with or prevent the development or exploitation of the Services, or any other website, application, content, submission, product, service, or intellectual property owned, licensed, used or controlled by any Indemnified Party.`,
	},
	{
		title: '13. Arbitration Agreement and Waiver of Rights',
		content: `Prior to commencing any legal proceeding against us of any kind, including an arbitration as set forth below, you and we agree that we will attempt to resolve any dispute, claim, or controversy between us arising out of or relating to the Agreement or the Services (each, a “Dispute” and, collectively, “Disputes”) by engaging in good faith negotiations. Such good faith negotiations require, at a minimum, that the aggrieved party provide a written notice to the other party specifying the nature and details of the Dispute. The party receiving such notice shall have thirty (30) days to respond to the notice. If the parties are unable to resolve the Dispute within ninety (90) days after the aggrieved party sent the initial notice, the parties may agree to mediate their Dispute, or either party may submit the Dispute to arbitration as set forth below.
You and we agree that any Dispute that cannot be resolved through the procedures set forth above will be resolved through binding arbitration in accordance with the International Arbitration Rules of the International Centre for Dispute Resolution (ICDR). The language of the arbitration shall be English. The arbitrator(s) shall have experience adjudicating matters involving internet technology, software applications, financial transactions and, ideally, blockchain technology. The arbitrator’s award of damages must be consistent with the terms of the “Limitation of Liability” section of this Agreement as to the types and amounts of damages for which a party may be held liable. The prevailing party will be entitled to an award of their reasonable attorney’s fees and costs. Except as may be required by law, neither a party nor its representatives may disclose the existence, content, or results of any arbitration hereunder without the prior written consent of (all/both) parties.`,
	},
	{
		title: '14. Class Action and Jury Trial Waiver',
		content: `You must bring any and all Disputes against us in your individual capacity and not as a plaintiff in or member of any purported class action, collective action, private attorney general action, or other representative proceeding. This provision applies to class arbitration. You and we both agree to waive the right to demand a trial by jury. Further, unless both you and we otherwise agree in writing, the arbitrator may not consolidate more than one person’s claims and may not otherwise preside over any form of any class or representative proceeding.`,
	},
	{
		title: '15. Modification of this Agreement',
		content: `We reserve the right to update or modify the Service, and any part of the Agreement from time to time for any reason, at our sole discretion. If we make any modifications, we will notify you by updating the date at the top of the Agreement and by maintaining a current version of the Agreement at [enter hyperlink]. We may, at any time, and without liability to you, modify or discontinue any or all parts of the Services (including access to the Services via any third-party links). All modifications will be effective when they are posted, and your continued use of the Protocol will serve as confirmation of your acceptance of those modifications. If you do not agree with any modifications to this Agreement, you must immediately stop accessing and using the Protocol.
You may contact us with questions about your use of the Services at hello@hashstack.finance. When you communicate with us electronically, you consent to receive communications from us electronically. You should review the Agreement from time to time to ensure that you understand the terms and conditions that apply to you when you access or use the Protocol.`,
	},
	{
		title: '16. Severability',
		content: `If any provision of the Agreement (including, without limitation, these Terms) is determined to be unlawful, void, or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from the Agreement. Such determination shall not affect the validity and enforceability of any other remaining provisions.`,
	},
	{
		title: '17. Termination; Cancellation',
		content: `This Agreement is effective unless and until terminated by either you or us. You may terminate your Agreement with us at any time by ceasing all access to the Protocol or the Services. If, in our sole judgment, you fail, or we suspect that you have failed, to comply with any term or provision of the Agreement (including without limitation any provision of this Agreement), we reserve the right to terminate our Agreement with you and deny you access to the Services. We further reserve the right to restrict your access to the Protocol or to stop providing you with all or a part of the Services at any time and for no reason, including, without limitation, if we reasonably believe: (a) your use of the Services exposes us to risk or liability; (b) you are using the Services for unlawful purposes; or (c) it is not commercially viable to continue providing you with our Services. All of these are in addition to any other rights and remedies that may be available to us, whether in equity or at law, all of which we expressly reserve.`,
	},
	{
		title: '18. Governing Law',
		content: `This Agreement is governed by the laws of British Virgin Islands, without regard to conflict of law rules or principles (whether of British Virgin Islands or any other jurisdiction) that would cause the application of the laws of any other jurisdiction.`,
	},
];
