name: Build & deploy [Testnet]

on:
  push:
    branches:
      - testnet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0
      - name: Install dependencies
        run: yarn
      
      - name: "Setup .env"
        run: |
          touch .env
          echo 'NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_SHEET_ID=${{secrets.NEXT_PUBLIC_GOOGLE_SHEET_ID}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_WALLETCONNECT=${{secrets.NEXT_PUBLIC_INFURA_WALLETCONNECT}}' >> .env
          echo 'NEXT_PUBLIC_WALLETCONNECT_PROJECTOR=${{secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECTOR}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_PRIVATE_KEY=${{secrets.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY}}' >> .env

      - name: Build
        run: yarn build
      - name: Export
        run: yarn export
        
      - name: Deploy
        run: aws s3 sync ./out s3://token.testnet.hashstack.finance
