name: Build & deploy [Mainnet]

on:
  push:
    branches:
      - mainnet-V1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: "Setup .env"
        run: |
          touch .env
          echo 'NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_SHEET_ID=${{secrets.NEXT_PUBLIC_GOOGLE_SHEET_ID}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_WALLETCONNECT=${{secrets.NEXT_PUBLIC_INFURA_WALLETCONNECT}}' >> .env
          echo 'NEXT_PUBLIC_WALLETCONNECT_PROJECTOR=${{secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECTOR}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_PRIVATE_KEY=${{secrets.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY}}' >> .env
          echo 'NEXT_PUBLIC_NODE_ENV=mainnet' >> .env
          echo 'NEXT_PUBLIC_TC_PRESALE=0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359' >> .env
          echo 'NEXT_PUBLIC_TC_USDC=0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359' >> .env
          echo 'NEXT_PUBLIC_TC_USDT=0xc2132D05D31c914a87C6611C10748AEb04B58e8F' >> .env
          
      - name: Install dependencies
        run: yarn
        
      - name: Build
        run: NEXT_PUBLIC_APP_ENV=production yarn build
        
      - name: Deploy
        run: aws s3 sync ./out s3://token.hashstack.finance

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E1K79STJ7XENGX
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
