name: Build & deploy [Production]

on:
  push:
    branches:
      - production

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: 'yarn'
      
      - name: 'Setup .env'
        run: |
          touch .env
          echo 'NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_EMAIL}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_SHEET_ID=${{secrets.NEXT_PUBLIC_GOOGLE_SHEET_ID}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_WALLETCONNECT=${{secrets.NEXT_PUBLIC_INFURA_WALLETCONNECT}}' >> .env
          echo 'NEXT_PUBLIC_WALLETCONNECT_PROJECTOR=${{secrets.NEXT_PUBLIC_WALLETCONNECT_PROJECTOR}}' >> .env
          echo 'NEXT_PUBLIC_GOOGLE_PRIVATE_KEY=${{secrets.NEXT_PUBLIC_GOOGLE_PRIVATE_KEY}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_TESTNET_BASE=${{secrets.NEXT_PUBLIC_INFURA_TESTNET_BASE}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_TESTNET_STARKNET=${{secrets.NEXT_PUBLIC_INFURA_TESTNET_STARKNET}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_MAINNET_STARKNET=${{secrets.NEXT_PUBLIC_INFURA_MAINNET_STARKNET}}' >> .env
          echo 'NEXT_PUBLIC_INFURA_MAINNET=${{secrets.NEXT_PUBLIC_INFURA_MAINNET}}' >> .env
          echo 'NEXT_PUBLIC_NODE_ENV=${{secrets.NEXT_PUBLIC_NODE_ENV}}' >> .env  
          echo 'NEXT_PUBLIC_TC_PRESALE=E574DA7E5F9249bd669a7C7E09b503973176f67e' >> .env
          echo 'NEXT_PUBLIC_MC_PRESALE=cD1946053a091C49e0365a968C2E34b22C00D0Fb' >> .env
          echo 'NEXT_PUBLIC_TC_USDC=0FA8781a83E46826621b3BC094Ea2A0212e71B23' >> .env
          echo 'NEXT_PUBLIC_TC_USDT=2bbf1f48a678d2f7c291dc5f8fd04805d34f485f' >> .env
          echo 'NEXT_PUBLIC_MC_USDT=c2132D05D31c914a87C6611C10748AEb04B58e8F' >> .env
          echo 'NEXT_PUBLIC_MC_USDC=3c499c542cEF5E3811e1192ce70d8cC03d5c3359' >> .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build
        run: NEXT_PUBLIC_APP_ENV=production yarn build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
